# Generated by Django 4.2.16 on 2026-06-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approval_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='conversion_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='current_load_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='display_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north_east', 'North East'), ('north_west', 'North West'), ('south_east', 'South East'), ('south_west', 'South West')], max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='is_corner_plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_gated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_length_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_includes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='road_width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='shop_depth_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='shop_frontage_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-Furnished'), ('furnished', 'Furnished')], default='unfurnished', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('shop', 'Shop'), ('site', 'Site/Plot')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.TextField(),
        ),
    ]
